[package]
name = "lpc81x-hal"
version = "0.1.0"
authors = ["Martin Atkins <mart@degeneration.co.uk>"]
edition = "2018"

[dependencies]
embedded-hal = { version = "0.2.3", features = ["unproven"] }
lpc81x-pac = "0.1.0"
void = "1.0.2"
