[package]
name    = "lpc81x"
version = "0.1.0"
authors = ["Martin Atkins <mart@degeneration.co.uk>"]
edition = "2018"

description   = "Hardware Abstraction Layer (HAL) for the NXP LPC81x series of ARM Cortex-M0+ microcontrollers"
documentation = "https://docs.rs/lpc81x"
repository    = "https://github.com/apparentlymart/rust-lpc81x"
license       = "0BSD"
readme        = "README.md"
categories    = ["embedded", "hardware-support", "no-std"]
keywords      = ["arm", "cortex-m", "nxp", "lpc", "embedded-hal-impl"]


[dependencies]
cortex-m     = "0.5.2"
embedded-hal = { version = "0.2", features = ["unproven"] }
lpc81x-pac   = "0.1.0"
nb           = "0.1.1"
void         = { version = "1", default-features = false }
# This should be in [dev-dependencies], but those can't be optional. Issue:
# https://github.com/rust-lang/cargo/issues/1596
compiletest_rs = { version = "0.3", optional = true }

[dev-dependencies]
cortex-m-rt = "0.6.3"
panic-abort = "0.3.1"


[features]
# This is needed to make the compiletest stuff optional. It requires std, which
# means we can't build it together with the examples.
compiletest = ["compiletest_rs"]
rt          = ["lpc81x-pac/rt"]


[[example]]
name              = "gpio"
required-features = ["rt"]


[lib]
test = false
bench = false


[profile.release]
incremental = false
lto         = true
opt-level   = "z"


[package.metadata.release]
pre-release-commit-message = "Release version {{version}}"
pro-release-commit-message = "Bump version to {{version}}"
tag-prefix                 = "v"
tag-message                = "Version {{version}}"
dev-version-ext            = "dev"
